openapi: 3.0.3
info:
  title: Easyapp API
  version: 1.0.0
  description: API documentation for easyapp
paths:
  /api/hello/:
    get:
      operationId: api_hello_retrieve
      summary: Hello message
      description: Get a hello world message
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloMessage'
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      summary: User registration
      description: Register a new member and obtain an authentication token.
      tags:
      - auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        '201':
          description: Member registered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          description: Validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/auth/login/:
    post:
      operationId: auth_login_create
      summary: Login
      description: Log in an existing member and obtain an authentication token.
      tags:
      - auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          description: Validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid username or password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      summary: Logout current member
      description: Log out the current authenticated member by invalidating their tokens.
      tags:
      - auth
      security:
      - TokenAuth: []
      responses:
        '200':
          description: Logout successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailMessage'
        '401':
          description: Authentication credentials were not provided or are invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/auth/me/:
    get:
      operationId: auth_me_retrieve
      summary: Get current member profile
      description: Get the profile of the current authenticated member.
      tags:
      - auth
      security:
      - TokenAuth: []
      responses:
        '200':
          description: Current member profile.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        '401':
          description: Authentication credentials were not provided or are invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/chat/messages/:
    get:
      operationId: chat_messages_list
      summary: Get chat message history
      description: Retrieve the history of messages in the group chat.
      tags:
      - chat
      security:
      - TokenAuth: []
      responses:
        '200':
          description: List of chat messages.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '401':
          description: Authentication credentials were not provided or are invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: chat_messages_create
      summary: Send a new chat message
      description: Send a new message to the group chat.
      tags:
      - chat
      security:
      - TokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessageCreateRequest'
      responses:
        '201':
          description: Message created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication credentials were not provided or are invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    HelloMessage:
      type: object
      properties:
        message:
          type: string
          maxLength: 200
        timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - message
      - timestamp
    Member:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 150
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - id
      - username
      - created_at
    MemberProfile:
      allOf:
      - $ref: '#/components/schemas/Member'
    Message:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        text:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        sender_username:
          type: string
          readOnly: true
      required:
      - id
      - text
      - created_at
      - sender_username
    RegistrationRequest:
      type: object
      properties:
        username:
          type: string
          maxLength: 150
        password:
          type: string
          format: password
      required:
      - username
      - password
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
      required:
      - username
      - password
    AuthTokenResponse:
      type: object
      properties:
        token:
          type: string
        member:
          $ref: '#/components/schemas/Member'
      required:
      - token
      - member
    DetailMessage:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    Error:
      allOf:
      - $ref: '#/components/schemas/DetailMessage'
    ChatMessageCreateRequest:
      type: object
      properties:
        text:
          type: string
      required:
      - text
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Use 'Token <key>' format in the Authorization header.
